name: 'Minecraft Resource Pack Upgrader'
description: 'Upgrades Minecraft resource packs to 1.21.4'
inputs:
  input_path:
    description: 'Path to the resource pack to upgrade'
    required: true
outputs:
  success:
    description: 'Whether upgrade succeeded'
branding:
  icon: 'package'
  color: 'green'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python app/upgrade.py ${{ inputs.input_path }}
      shell: bash
