name: Update README with Latest Version

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README.md with latest version
      run: |
        LATEST_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        sed -i "s/AshleyThew\/minecraft-resource-pack-upgrader@v[0-9.]\+/AshleyThew\/minecraft-resource-pack-upgrader@$LATEST_VERSION/" readme.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add readme.md
        git commit -m "Update README.md with latest version $LATEST_VERSION"
        git push